version = "5.1.1" # match the nixpkgs version of ghdl -- nix eval .#ghdl.version

[x86_64-darwin]
platform_double = "macos13-x86_64"
sha256 = "sha256-TDWp1gKNEcv8eyqY4M2yilbiaOX1htckaQT+xAvIGTo="

[aarch64-darwin]
platform_double = "macos14-aarch64"
sha256 = "sha256-6Fij7jzuIsl2NU7npmq2N3vuwak4NGLwulg6jfc/RsE="

[x86_64-linux]
platform_double = "ubuntu24.04-x86_64"
sha256 = "sha256-fAHWj6Y/fgNybHwInWBWXwTSfV6JZrziPXKGvw7O5w0="
